### ISSUE TITLE
Problems that occur during operation

### ISSUE THREAD

**Issue by PlutoXN** [comflife/Realtime_yolopv2#2]
Traceback (most recent call last):
  File "/home/nby/Research/YOLOPv3-main/realtime.py", line 182, in <module>
    detect()
  File "/home/nby/Research/YOLOPv3-main/realtime.py", line 171, in detect
    inference(img, im0s, path)
  File "/home/nby/Research/YOLOPv3-main/realtime.py", line 94, in inference
    [pred, anchor_grid], seg, ll = model(img)
  File "/home/nby/anaconda3/envs/YOLOPV2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() Expected a value of type 'Tensor' for argument 'input' but instead found type 'ndarray'.
Position: 1
Value: array([[[114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        ...,
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114]],

       [[114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        ...,
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114]],

       [[114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        ...,
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114],
        [114, 114, 114, ..., 114, 114, 114]]], dtype=uint8)
Declaration: forward(__torch__.models.yolo.Model self, Tensor input) -> (((Tensor[], (Tensor, Tensor, Tensor)), Tensor, Tensor))
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

**Comment by comflife** [comment]
Sorry for the late reply, but have you tried putting --source 0 after the vs code you want to run? Or maybe you could try replacing the video part with 0,1,2 inside the code. I'm busy for a while, so I'm late updating the code, so I'll fix it more within 1 or 2 weeks. The difference with the existing yolopv2 is that there was no realtime code with a webcam before, but in this repo, I made it and added additional features such as lane recognition and driving with a webcam through ROS2 communication, and ROI to see only the part you want to see. For personal reasons, I will upload it in 1,2 weeks, so I would be very grateful if you have a lot of interest.

**Comment by PlutoXN** [comment]
Your project is great, when trying out the BEV file, the input data to the model function doesn't seem to match the type. The sentence [pred,anchor_grid], seg, ll = model(img) reports an error at runtime: RuntimeError:forward() Expected a value of type 'Tensor' for argument 'input' but instead finds the type 'ndarray'.Lookingforward. About BEV code hopes that you can release some demos and look forward to the release of your project!

**Comment by comflife** [comment]
Sorry for late comment. I solved errors and It will work well. --source 0 like this, change 0 to your webcam number.
